import { z } from 'zod';

export const jobDataSchema = z.object({
  Code: z.string(),
  Title: z.string(),
  Definitions: z.string().optional(),
  Industry: z.string().optional(),
  AltTitles: z.string().optional(),
  SVPNum: z.number().optional(),
  Strength: z.string().optional(),
  GOE: z.string().optional(),
  ClimbingNum: z.number().optional(),
  BalancingNum: z.number().optional(),
  StoopingNum: z.number().optional(),
  KneelingNum: z.number().optional(),
  CrouchingNum: z.number().optional(),
  CrawlingNum: z.number().optional(),
  ReachingNum: z.number().optional(),
  HandlingNum: z.number().optional(),
  FingeringNum: z.number().optional(),
  FeelingNum: z.number().optional(),
  TalkingNum: z.number().optional(),
  HearingNum: z.number().optional(),
  TastingNum: z.number().optional(),
  NearAcuityNum: z.number().optional(),
  FarAcuityNum: z.number().optional(),
  DepthNum: z.number().optional(),
  AccommodationNum: z.number().optional(),
  ColorVisionNum: z.number().optional(),
  FieldVisionNum: z.number().optional(),
  WeatherNum: z.number().optional(),
  ColdNum: z.number().optional(),
  HeatNum: z.number().optional(),
  WetNum: z.number().optional(),
  NoiseNum: z.number().optional(),
  VibrationNum: z.number().optional(),
  AtmosphereNum: z.number().optional(),
  MovingNum: z.number().optional(),
  ElectricityNum: z.number().optional(),
  HeightNum: z.number().optional(),
  RadiationNum: z.number().optional(),
  ExplosionNum: z.number().optional(),
  ToxicNum: z.number().optional(),
  OtherNum: z.number().optional(),
  GEDR: z.number().optional(),
  GEDM: z.number().optional(),
  GEDL: z.number().optional(),
  WFData: z.number().optional(),
  WFDataSig: z.string().optional(),
  WFPeople: z.number().optional(),
  WFPeopleSig: z.string().optional(),
  WFThings: z.number().optional(),
  WFThingsSig: z.string().optional(),
  WField1: z.string().optional(),
  WField1Short: z.string().optional(),
  MPSMS1: z.string().optional(),
  MPSMS1Short: z.string().optional(),
  Temp1: z.string().optional(),
  Temp2: z.string().optional(),
  Temp3: z.string().optional(),
  Temp4: z.string().optional(),
  Temp5: z.string().optional(),
});

export type JobDataSchema = z.infer<typeof jobDataSchema>;